boats/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from . import views
app_name = 'boats'
urlpatterns = [
	url(r'^boat/(?P<boat_id>[0-9]+)/$', views.view_boat, name='view_boat'),
	url(r'^engine/(?P<engine_id>[0-9]+)/$', views.view_engine, name='view_engine'),
	url(r'^uploadboatimage/(?P<boat_id>[0-9]+)/$', views.upload_boat_image, name='upload_boat_image'),
	url(r'^updateboat/(?P<boat_id>[0-9]+)/$', views.update_boat, name='update_boat'),
	url(r'^updateengine/(?P<engine_id>[0-9]+)/$', views.update_engine, name='update_engine'),
	url(r'^engineservice/(?P<engine_id>[0-9]+)/$', views.add_service, name='update_service'),
	url(r'^deleteboatimage/(?P<image_id>[0-9]+)/$', views.delete_boat_image, name='delete_boat_image'),
	url(r'^addboat/$', views.add_boat, name='add_boat'),
	url(r'^addengine/$', views.add_engine, name='add_engine'),
	url(r'^createboat/$', views.create_boat, name='create_boat'),
	url(r'^createengine/$', views.create_engine, name='create_engine'),
	url(r'^engines/$', views.index_engines, name='engines_index'),
    url('', views.index, name='index'),
]

powerboatsapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^login/$', auth_views.login, {'template_name': 'login.html'},name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^internal/boats/', include('boats.urls')),
    url(r'^internal/members/', include('racers.urls')),
    url(r'^internal/sponsors/', include('sponsors.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boats/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

#
# Engine Information
#

class EngineServices(models.Model):
	service_date = models.DateField()
	next_service = models.DateField()
	notes = models.TextField(null=True)

class Engine(models.Model):
	serial_number  = models.CharField(max_length=250)
	build_year = models.DateField()
	services = models.ManyToManyField(EngineServices)
	make = models.CharField(max_length=250,null=True)

	def next_service(self):
		try:
			service_date = (self.services.all().order_by('-next_service')[0]).next_service
		except:
			service_date = datetime.now()

		return service_date

	def current_boat(self):
		try:
			boat = self.boat_set.all()[0]
		except:
			boat = None
		return boat

	def service_nat(self):
		exp_dt = datetime.strptime((self.next_service()).strftime('%Y-%m-%d'), '%Y-%m-%d').strftime('%Y-%m-%dT%H:%M:%S.%f')
		exp_dt = datetime.strptime(exp_dt, '%Y-%m-%dT%H:%M:%S.%f')
		return exp_dt

#
# Boat
#

class BoatImages(models.Model):
	boat_image = models.FileField(upload_to='boats')
	profile_image = models.BooleanField(default=False)
	caption = models.TextField(null=True)
	title = models.CharField(max_length=250,null=True)

	def __unicode__(self):
		return self.title

class HullColours(models.Model):
	colour = models.CharField(max_length=250)

	def __unicode__(self):
		return self.colour

class BoatOwners(models.Model):
	company_name = models.CharField(max_length=250, null=True)
	person_name = models.ForeignKey(User, null=True)

	def display_name(self):
		if self.company_name:
			return self.company_name
		else:
			return ' '.join([self.person_name.first_name, self.person_name.last_name])


class Boat(models.Model):
	registration = models.CharField(max_length=250, null=True)
	hull_colour = models.ForeignKey(HullColours, null=True)
	owner = models.ForeignKey(BoatOwners, null=True)
	replacement_value = models.CharField(max_length=250, null=True)
	insured = models.BooleanField(default=False)
	insurance_policy = models.CharField(max_length=250, null=True)
	engine = models.ForeignKey(Engine, null=True)
	images = models.ManyToManyField(BoatImages)
	build_date = models.DateField(null=True)

	def insurance_display(self):
		if self.insured == True:
			return ' '.join(['Insured', self.insurance_policy])
		else:
			return 'Uninsured'

	def profile_image(self):
		try:
			profile_image = ((self.images.filter(profile_image=True))[0]).boat_image
		except:
			profile_image = ""

		return profile_image

boats/forms.py
from django import forms
from .models import *

class PhotoForm(forms.Form):
	boat_image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class BoatForm(forms.Form):
	boat_registration = forms.CharField(required=False)
	hull_colour = forms.CharField(required=False)
	owner = forms.CharField(required=False)
	current_value = forms.CharField(required=False)
	insured = forms.CharField(required=False)
	insurance_policy = forms.CharField(required=False)
	engine_serial = forms.CharField(required=False)
	build_date = forms.CharField(required=False)
	
class EngineForm(forms.Form):
	make = forms.CharField(required=False)
	serial_number = forms.CharField(required=False)
	build_date = forms.CharField(required=False)
	current_boat = forms.CharField(required=False)

class ServiceForm(forms.Form):
	service_date = forms.CharField(required=False)
	next_service = forms.CharField(required=False)
	service_note = forms.CharField(widget=forms.Textarea, required=False)

boats/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views import View
from datetime import datetime
from django.urls import reverse
from .forms import *
from .models import *
# Create your views here.

@login_required(login_url='/login/')
def index(request):
	boats = Boat.objects.all()
	context = {
    	'boats' : boats,
	}
	template = loader.get_template('boats/index.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def index_engines(request):
	engines = Engine.objects.all()
	context = {
    	'engines' : engines,
	}
	template = loader.get_template('boats/engines_index.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def view_engine(request,engine_id):
	engine = Engine.objects.get(id=engine_id)
	services = engine.services.all().order_by('-next_service')
	context = {
		'engine' : engine,
		'services' : services,
	}
	template = loader.get_template('boats/view_engine.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def view_boat(request,boat_id):
	boat = Boat.objects.get(id=boat_id)
	services = boat.engine.services.all().order_by('-service_date')
	hull_cols = HullColours.objects.all()
	eng_sers = Engine.objects.all()
	owners = BoatOwners.objects.all()
	form = BoatForm()
	context = {
    	'boat' : boat,
    	'services' : services,
    	'hull_cols' : hull_cols,
		'eng_sers' : eng_sers,
		'owners' : owners,
		'form' : form,
	}
	template = loader.get_template('boats/view.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def add_boat(request):
	hull_cols = HullColours.objects.all()
	eng_sers = Engine.objects.all()
	owners = BoatOwners.objects.all()
	form = BoatForm()
	context = {
    	'hull_cols' : hull_cols,
		'eng_sers' : eng_sers,
		'owners' : owners,
		'form' : form,
	}
	template = loader.get_template('boats/addboat.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def add_engine(request):
	boats = Boat.objects.all()

	context = {
    	'boats' : boats,
	}
	template = loader.get_template('boats/addengine.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def create_engine(request):
	if request.method == "POST":
		form = EngineForm(request.POST)
		if form.is_valid():
			make = form.cleaned_data['make']
			serial_number = form.cleaned_data['serial_number']
			build_year = datetime.strptime(form.cleaned_data['build_date'], "%d/%m/%Y")
			
			engine = Engine(make=make, serial_number=serial_number, build_year=build_year)
			engine.save()
			
			if not form.cleaned_data['current_boat'] == "":
				boat = Boat.objects.get(id=(form.cleaned_data['current_boat'].split("[")[1]).split("]")[0])
				boat.engine = engine
				boat.save()

			return HttpResponseRedirect(reverse('boats:view_engine', kwargs={'engine_id' : engine.id}))

@login_required(login_url='/login/')
def create_boat(request):

	if request.method == "POST":
		form = BoatForm(request.POST)
		if form.is_valid():
			boat =Boat(registration = form.cleaned_data['boat_registration'])
			boat.hull_colour = HullColours.objects.get(id=(form.cleaned_data['hull_colour'].split("[")[1]).split("]")[0])
			boat.boat_owner = BoatOwners.objects.get(id=(form.cleaned_data['owner'].split("[")[1]).split("]")[0])
			boat.engine = Engine.objects.get(id=(form.cleaned_data['engine_serial'].split("[")[1]).split("]")[0])
			boat.build_date = datetime.strptime(form.cleaned_data['build_date'], "%d/%m/%Y")
			if form.cleaned_data['insured'] == "Yes":
				boat.insured = True
				boat.insurance_policy = form.cleaned_data['insurance_policy']
			else:
				boat.insured = False
				boat.insurance_policy = ""
			boat.current_value = form.cleaned_data['current_value']

			boat.save()

	return HttpResponseRedirect(reverse('boats:view_boat', kwargs={'id' : boat.id}))

@login_required(login_url='/login/')
def update_boat(request, boat_id):

	if request.method == "POST":
		form = BoatForm(request.POST)
		boat = Boat.objects.get(id=boat_id)
		if form.is_valid():
			boat.registration = form.cleaned_data['boat_registration']
			boat.hull_colour = HullColours.objects.get(id=(form.cleaned_data['hull_colour'].split("[")[1]).split("]")[0])
			boat.owner = BoatOwners.objects.get(id=(form.cleaned_data['owner'].split("[")[1]).split("]")[0])
			boat.engine = Engine.objects.get(id=(form.cleaned_data['engine_serial'].split("[")[1]).split("]")[0])
			boat.build_date = datetime.strptime(form.cleaned_data['build_date'], "%d/%m/%Y")
			if form.cleaned_data['insured'] == "Yes":
				boat.insured = True
				boat.insurance_policy = form.cleaned_data['insurance_policy']
			else:
				boat.insured = False
				boat.insurance_policy = ""
			boat.current_value = form.cleaned_data['current_value']

			boat.save()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def add_service(request,engine_id):
	engine = Engine.objects.get(id=engine_id)

	if request.method == "POST":
		form = ServiceForm(request.POST)
		if form.is_valid():
			service_date = datetime.strptime(form.cleaned_data['service_date'], "%d/%m/%Y")
			next_service = datetime.strptime(form.cleaned_data['next_service'], "%d/%m/%Y")
			service_notes = form.cleaned_data['service_note']
			service = EngineServices(service_date=service_date,next_service=next_service,notes=service_notes)
			service.save()
			engine.services.add(service)
			engine.save()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))		

@login_required(login_url='/login/')
def update_engine(request,engine_id):

	if request.method == "POST":
		form = EngineForm(request.POST)
		engine = Engine.objects.get(id=engine_id)
		if form.is_valid():
			build_date = datetime.strptime(form.cleaned_data['build_date'], "%d/%m/%Y")
			engine.make = form.cleaned_data['make']
			engine.serial_number = form.cleaned_data['serial_number']
			engine.build_year = build_date
			print(engine.build_year)
			engine.save()
			boat = Boat.objects.get(id=(form.cleaned_data['current_boat'].split("[")[1]).split("]")[0])
			boat.engine = engine
			boat.save()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def upload_boat_image(request, boat_id):
	boat = Boat.objects.get(id=boat_id)
	if request.method == "POST":
		form = PhotoForm(request.POST, request.FILES)
		files = request.FILES.getlist('boat_image')
		if form.is_valid():
			for f in files:
				boat_image = BoatImages(boat_image=f)
				boat_image.save()
				boat.images.add(boat_image)
				boat.save()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def delete_boat_image(request, image_id):
	boat_image = BoatImages.objects.get(id=image_id).delete()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

class BasicUploadView(View):
    def get(self, request):
        photos_list = BoatImages.objects.all()
        return render(self.request, 'photos/basic_upload/index.html', {'photos': photos_list})

    def post(self, request):
		form = PhotoForm(self.request.POST, self.request.FILES)
		files = request.FILES.getlist('boat_image')
		if form.is_valid():
			
			for f in files:
				print(f)
			return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
		else:
			print(form.errors)
			data = {'is_valid': False}
			return JsonResponse(data)

boats/templates/boats/addboat.html
{% extends "base_site.html" %}
{% load humanize %}
{% block title %} New Boat {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">

    <div class="page-title">
        <div class="title_left">
          <h3>New Boat</h3>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel tile">
          <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a id="boat_edit" href="#"><i class="fa fa-pencil"></i></a>
                  
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
          
          <div class="x_content">
            <div class="row">
              <form id="boat_form" method="post" action="{% url 'boats:create_boat' %}" data-parsley-validate class="form-horizontal form-label-left">
                {% csrf_token %}
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Boat Registration <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input id="id_boat_registration" name="boat_registration" type="text" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Build Date <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input id="id_build_date" name="build_date" type="text" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Hull Colour <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="hull_colour" required="required" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Owner <span class="required">*</span>
                  </label>
                  <div class="col-md-3 col-sm-3 col-xs-12">
                    <input type="text" id="id_owner" name="owner" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">Current Value <span class="required">*</span>
                  </label>
                  <div class="col-md-1 col-sm-1 col-xs-12">
                    <input type="text" id="id_current_value" name="current_value" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12">Insured</label>
                  <div class="col-md-2 col-sm-2 col-xs-12">
                    <div id="gender" class="btn-group" data-toggle="buttons">
                      <label id="yes_button" class="btn btn-default active" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                        <input type="radio" name="gender" value="Yes"> Yes
                      </label>
                      <label id="no_button" class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                        <input type="radio"  name="gender" value="No"> No &nbsp
                      </label>
                      <input id="id_insured" value="No" name="insured" style="display: none;">
                    </div>
                  </div>
                  <label class="control-label col-md-1 col-sm-1 col-xs-12" for="first-name">Policy <span class="required">*</span></label>
                  <div class="col-md-3 col-sm-3 col-xs-12">
                    <input type="text" id="id_insurance_policy" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Engine <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_engine_serial" name="engine_serial" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    <button type="submit" class="btn btn-danger btn-round" id="submit_button" >Create Boat</button>
                  </div>
                </div>
              </form>
            </div>
            
        </div>
      </div>
    </div>   
  </div>
  

</div>

<script>
function init_colours() {

    var colours = { {% for col in hull_cols %}{{ col.id}} : "{{col.colour}} [{{ col.id }}]", {% endfor %}};

    var coloursArray = $.map(colours, function(value, key) {
        return {
            value: value,
            data: key
        };
    });

    // initialize autocomplete with custom appendTo
    $('#id_hull_colour').autocomplete({
        lookup: coloursArray
    });

};

function init_eng_ser() {

    var serials = { {% for ser in eng_sers %}{{ ser.id}} : "{{ser.make}}: {{ser.serial_number}} [{{ser.id}}]", {% endfor %}};

    var serialsArray = $.map(serials, function(value, key) {
        return {
            value: value,
            data: key
        };
    });

    // initialize autocomplete with custom appendTo
    $('#id_engine_serial').autocomplete({
        lookup: serialsArray
    });

};

function init_owners() {

    var owners = { {% for own in owners %}{{ own.id}} : "{{own.display_name}} [{{ own.id }}]", {% endfor %}};

    var ownersArray = $.map(owners, function(value, key) {
        return {
            value: value,
            data: key
        };
    });

    // initialize autocomplete with custom appendTo
    $('#id_owner').autocomplete({
        lookup: ownersArray
    });

};


</script>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- Chart.js -->
  <script src="/static/vendors/Chart.js/dist/Chart.min.js"></script>
  <!-- gauge.js -->
  <script src="/static/vendors/gauge.js/dist/gauge.min.js"></script>
  <!-- Skycons -->
  <script src="/static/vendors/skycons/skycons.js"></script>
  <!-- Flot -->
  <script src="/static/vendors/Flot/jquery.flot.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.pie.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.time.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.stack.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.resize.js"></script>
  <!-- Flot plugins -->
  <script src="/static/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
  <script src="/static/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
  <script src="/static/vendors/flot.curvedlines/curvedLines.js"></script>
  <!-- DateJS -->
  <script src="/static/vendors/DateJS/build/date.js"></script>
  <!-- JQVMap -->
  <script src="/static/vendors/jqvmap/dist/jquery.vmap.js"></script>
  <script src="/static/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
  <script src="/static/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
  <!-- Data Tables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
  <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
  <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
  <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>
  <!-- File Upload -->
  <script src="/static/vendors/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
  <script src="/static/vendors/jquery-file-upload/js/jquery.iframe-transport.js"></script>
  <script src="/static/vendors/jquery-file-upload/js/jquery.fileupload.js"></script>

  <script>
    $(document).ready(function() {
  init_colours();
  init_eng_ser();
  init_owners();

 

    $("#no_button").on("click", function(event) {
        $('#id_insured').val("No")  
    });

    $("#yes_button").on("click", function(event) {
        $('#id_insured').val("Yes")  
    });
});
  </script>

{% endblock javascripts %}