boats/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from . import views
app_name = 'boats'
urlpatterns = [
	url(r'^boat/(?P<boat_id>[0-9]+)/$', views.view_boat, name='view_boat'),
	url(r'^engine/(?P<engine_id>[0-9]+)/$', views.view_engine, name='view_engine'),
	url(r'^uploadboatimage/(?P<boat_id>[0-9]+)/$', views.upload_boat_image, name='upload_boat_image'),
	url(r'^updateboat/(?P<boat_id>[0-9]+)/$', views.update_boat, name='update_boat'),
	url(r'^updateengine/(?P<engine_id>[0-9]+)/$', views.update_engine, name='update_engine'),
	url(r'^engineservice/(?P<engine_id>[0-9]+)/$', views.add_service, name='update_service'),
	url(r'^deleteboatimage/(?P<image_id>[0-9]+)/$', views.delete_boat_image, name='delete_boat_image'),
	url(r'^addboat/$', views.add_boat, name='add_boat'),
	url(r'^addengine/$', views.add_engine, name='add_engine'),
	url(r'^createboat/$', views.create_boat, name='create_boat'),
	url(r'^createengine/$', views.create_engine, name='create_engine'),
	url(r'^engines/$', views.index_engines, name='engines_index'),
    url('', views.index, name='index'),
]

drivers/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from . import views

urlpatterns = [
    url('', views.index, name='index'),
]

powerboatsapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^login/$', auth_views.login, {'template_name': 'login.html'},name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^internal/boats/', include('boats.urls')),
    url(r'^internal/members/', include('racers.urls')),
    url(r'^internal/sponsors/', include('sponsors.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drivers/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

#
# Racing Licenses
# 

class RacingLicenseTypes(models.Model):
	name = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name 

class RacingLicenseScans(models.Model):
	file = models.FileField(upload_to='media/licenses')
	expires = models.DateField()
	uploaded_date = models.DateTimeField(auto_now_add=True)

#
# Identity Documents
#

class IdentityTypes(models.Model):
	name = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name 

class IdentityScans(models.Model):
	file = models.FileField(upload_to='media/identity')
	expires = models.DateField()
	uploaded_date = models.DateTimeField(auto_now_add=True)
	identity_type = models.ForeignKey(IdentityTypes)

#
# Driver Profile Images
#

class DriverProfile(models.Model):
	file = models.FileField(upload_to='media/profile')
	expires = models.DateField()
	uploaded_date = models.DateTimeField(auto_now_add=True)
	profile_image = models.BooleanField(default=False)

class CareerVictory(models.Model):
	name = models.CharField(max_length=250)
	location = CountryField(null=True)
	team = models.CharField(max_length=250, null=True)
	year = models.CharField(max_length=250)
	position = models.CharField(max_length=2)

#
# Drivers Main Model
#

drivers/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login/')
def index(request):
	drivers = Driver.objects.all()

    context = {
    	'drivers' : drivers,
    }
    
    template = loader.get_template('drivers/index.html')
    return HttpResponse(template.render(context, request))

drivers/templates/drivers/index.html
{% extends "base_site.html" %}

{% block title %} Boats Administration {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="page-title">
        <div class="title_left">
          <h3>APA Driver Profiles</h3>
        </div>
    </div>
    
    {% for driver in drivers %}
    <div class="row">
      <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="x_panel tile">
          <div class="x_title">
            <h2>{{ boat.registration }}</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="thumbnail">
              <div class="image view view-first">
                <img style="width: 100%; display: block;" src="{{ boat.profile_image.url }}" alt="image" />    
              </div>
            </div>
            <table class="countries_list">
              <tbody>
                <tr>
                  <td>Name</td>
                  <td class="fs15 fw700 text-right">{{ boat.build_date|date:"d/m/Y" }}</td>
                </tr>
                <tr>
                  <td>Nationality</td>
                  <td class="fs15 fw700 text-right">{{ boat.hull_colour.colour }}</td>
                </tr>
                <tr>
                  <td>E-mail</td>
                  <td class="fs15 fw700 text-right">{{ boat.owner.display_name }}</td>
                </tr>
                <tr>
                  <td>Telephone</td>
                  <td class="fs15 fw700 text-right">{{ boat.insurance_display }}</td>
                </tr>
                <tr>
                  <td>Member Since</td>
                  <td class="fs15 fw700 text-right">{{ boat.engine.make }} ({{ boat.engine.serial_number }})</td>
                </tr>
              </tbody>
            </table>
            <p align="center"><a href="{% url 'boats:view_boat' boat_id='1' %}" class="btn btn-round btn-danger">Modify Boat</a></p>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
      
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- Chart.js -->
  <script src="/static/vendors/Chart.js/dist/Chart.min.js"></script>
  <!-- gauge.js -->
  <script src="/static/vendors/gauge.js/dist/gauge.min.js"></script>
  <!-- Skycons -->
  <script src="/static/vendors/skycons/skycons.js"></script>
  <!-- Flot -->
  <script src="/static/vendors/Flot/jquery.flot.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.pie.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.time.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.stack.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.resize.js"></script>
  <!-- Flot plugins -->
  <script src="/static/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
  <script src="/static/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
  <script src="/static/vendors/flot.curvedlines/curvedLines.js"></script>
  <!-- DateJS -->
  <script src="/static/vendors/DateJS/build/date.js"></script>
  <!-- JQVMap -->
  <script src="/static/vendors/jqvmap/dist/jquery.vmap.js"></script>
  <script src="/static/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
  <script src="/static/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
  <!-- Data Tables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
  <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
  <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
  <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>
{% endblock javascripts %}