boats/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from . import views
app_name = 'boats'
urlpatterns = [
	url(r'^boat/(?P<boat_id>[0-9]+)/$', views.view_boat, name='view_boat'),
	url(r'^engine/(?P<engine_id>[0-9]+)/$', views.view_engine, name='view_engine'),
	url(r'^uploadboatimage/(?P<boat_id>[0-9]+)/$', views.upload_boat_image, name='upload_boat_image'),
	url(r'^updateboat/(?P<boat_id>[0-9]+)/$', views.update_boat, name='update_boat'),
	url(r'^updateengine/(?P<engine_id>[0-9]+)/$', views.update_engine, name='update_engine'),
	url(r'^engineservice/(?P<engine_id>[0-9]+)/$', views.add_service, name='update_service'),
	url(r'^deleteboatimage/(?P<image_id>[0-9]+)/$', views.delete_boat_image, name='delete_boat_image'),
	url(r'^addboat/$', views.add_boat, name='add_boat'),
	url(r'^addengine/$', views.add_engine, name='add_engine'),
	url(r'^createboat/$', views.create_boat, name='create_boat'),
	url(r'^createengine/$', views.create_engine, name='create_engine'),
	url(r'^engines/$', views.index_engines, name='engines_index'),
    url('', views.index, name='index'),
]

powerboatsapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^login/$', auth_views.login, {'template_name': 'login.html'},name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^internal/boats/', include('boats.urls')),
    url(r'^internal/members/', include('racers.urls')),
    url(r'^internal/sponsors/', include('sponsors.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sponsors/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from . import views
app_name = 'sponsors'
urlpatterns = [
	url(r'add/$', views.add_sponsor, name='add_sponsor'),
    url('', views.index, name='index'),
]

sponsors/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from racers.models import *
from boats.models import *

# Create your models here.

class SponsorLogo(models.Model):
	image = models.FileField(upload_to='sponsors/logos')

class SponsorContracts(models.Model):
	name = models.CharField(max_length=250)
	file_contract = models.FileField(upload_to='sponsors/contracts')

	def __unicode__(self):
		return self.name 

class SponsorBenefits(models.Model):
	name = models.CharField(max_length=250)
	value = models.CharField(max_length=250, null=True)

	def __unicode__(self):
		return self.name

class SoponsorshipLevel(models.Model):
	name = models.CharField(max_length=250)
	value = models.CharField(max_length=250)
	benefits = models.ManyToManyField(SponsorBenefits)

	def __unicode__(self):
		return self.name

class SponsorPayments(models.Model):
	amount = models.CharField(max_length=250)
	date = models.DateField(auto_now_add=True)


class Sponsors(models.Model):
	member_link = models.ForeignKey(Members, null=True)
	sponsor_name = models.CharField(max_length=250)
	logo = models.ManyToManyField(SponsorLogo)
	email_address = models.EmailField(max_length=254)
	active_sponsor = models.BooleanField(default=True)
	contract = models.ManyToManyField(SponsorContracts)
	payments = models.ManyToManyField(SponsorPayments)
	driver_sponsor = models.BooleanField(default=False)
	driver_sponsored = models.CharField(max_length=250, null=True)
	boat_sponsored = models.ManyToManyField(Boat)

boats/forms.py
from django import forms
from .models import *

class PhotoForm(forms.Form):
	boat_image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class BoatForm(forms.Form):
	boat_registration = forms.CharField(required=False)
	hull_colour = forms.CharField(required=False)
	owner = forms.CharField(required=False)
	current_value = forms.CharField(required=False)
	insured = forms.CharField(required=False)
	insurance_policy = forms.CharField(required=False)
	engine_serial = forms.CharField(required=False)
	build_date = forms.CharField(required=False)
	
class EngineForm(forms.Form):
	make = forms.CharField(required=False)
	serial_number = forms.CharField(required=False)
	build_date = forms.CharField(required=False)
	current_boat = forms.CharField(required=False)

class ServiceForm(forms.Form):
	service_date = forms.CharField(required=False)
	next_service = forms.CharField(required=False)
	service_note = forms.CharField(widget=forms.Textarea, required=False)

racers/forms.py
from django import forms
from .models import *

class PersonForm(forms.Form):
	phonenumber = forms.CharField(required=False)
	dob = forms.CharField(required=False)
	nationality = forms.CharField(required=False)
	address_1 = forms.CharField(required=False)
	address_2 = forms.CharField(required=False)
	address_3 = forms.CharField(required=False)
	address_4 = forms.CharField(required=False)
	home_country = forms.CharField(required=False)
	personal = forms.CharField(required=False)
	facebook = forms.CharField(required=False)
	twitter = forms.CharField(required=False)
	instagram = forms.CharField(required=False)

class EventForm(forms.Form):
	event = forms.CharField(required=False)
	event_location = forms.CharField(required=False)
	team = forms.CharField(required=False)
	year = forms.CharField(required=False)
	position = forms.CharField(required=False)

class ProfileForm(forms.Form):
	profile_text = forms.CharField(widget=forms.Textarea)

class LicenseForm(forms.Form):
	license = forms.FileField(widget=forms.ClearableFileInput())
	expiry_date = forms.CharField(required=False)
	licensetype = forms.CharField(required=False)

class IdentityForm(forms.Form):
	identity = forms.FileField(widget=forms.ClearableFileInput())
	expiry_date = forms.CharField(required=False)
	identitytype = forms.CharField(required=False)

sponsors/forms.py
from django import forms
from .models import *

class SponsorForm(forms.Form):
	phonenumber = forms.CharField(required=False)
	sponsor_name = forms.CharField(required=False)
	logo = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': False}))
	email_address = forms.CharField(required=False)
	address_1 = forms.CharField(required=False)
	address_2 = forms.CharField(required=False)
	address_3 = forms.CharField(required=False)
	address_4 = forms.CharField(required=False)
	country = forms.CharField(required=False)
	phonenumber = forms.CharField(required=False)
	profile_text = forms.CharField(widget=forms.Textarea(), required=False)
	facebook = forms.CharField(required=False)
	twitter = forms.CharField(required=False)
	instagram = forms.CharField(required=False)
	website = forms.CharField(required=False)

sponsors/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views import View
from datetime import datetime
from django.urls import reverse
from django_countries.fields import Country, countries
from .forms import *
from .models import *
from racers.models import *

# Create your views here.
@login_required(login_url='/login/')
def index(request):

	context = {

	}
	template = loader.get_template('sponsors/index.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def add_sponsor(request):

	context = {
		'countries' : countries,

	}
	template = loader.get_template('sponsors/addsponsor.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def new_sponsor(request):
	if request.method == "POST":
		form = SponsorForm(request.POST, request.FILES)
		file = request.POST.get('logo')
		if form.is_valid():
			new_sponsor = Sponsors(sponsor_name = form.cleaned_data['sponsor_name'])
			new_sponsor.logo = file
			new_sponsor.email_address = form.cleaned_data['email']
			new_member = Members(address_line_1=form.cleaned_data['address_1'])
			new_member.address_2 = form.cleaned_data['address_2']
			new_member.address_3 = form.cleaned_data['address_3']
			new_member.address_4 = form.cleaned_data['address_4']
			new_member.country = form.cleaned_data['country'].split("[")[1].split("]")[0]
			new_member.address_country = form.cleaned_data['country'].split("[")[1].split("]")[0]
			new_member.telephone_number = form.cleaned_data['phonenumber']
			new_member.sponsor = True
			new_member.profile_text = form.cleaned_data['profile_text']
			new_member.facebook_handle = form.cleaned_data['facebook']
			new_member.twitter_handle = form.cleaned_data['twitter']
			new_member.insta_handle = form.cleaned_data['instagram']
			new_member.personal_site = form.cleaned_data['website']
			new_member.save()
			new_sponsor.member_link = new_member
			new_sponsor.save()
			
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

sponsors/templates/sponsors/addsponsor.html
{% extends "base_site.html" %}
{% load humanize %}
{% block title %} New Boat {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">

    <div class="page-title">
        <div class="title_left">
          <h3>New Sponsor</h3>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel tile">
          <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a id="boat_edit" href="#"><i class="fa fa-pencil"></i></a>
                  
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
          
          <div class="x_content">
            <div class="row">
              <form id="boat_form" method="post" action="{% url 'sponsors:add_sponsor' %}" data-parsley-validate class="form-horizontal form-label-left" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Sponsor Name <span class="required">*</span>
                  </label>
                  <div class="col-md-4 col-sm-4 col-xs-12">
                    <input id="id_boat_registration" name="sponsor_name" type="text" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                  <div class="col-md-1 col-sm-1 col-xs-12">
                    <button id="btn_id" style="" type="button" class="btn btn-danger btn-round" style="width: 100%;">
                      <span class="glyphicon glyphicon-cloud-upload"></span> Upload Logo
                    </button>                 
                  <input id="id_license" type="file" name="logo" multiple data-url="" data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}' enctype="multipart/form-data" style="display: none;">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Contact Person <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input name="contact_person" type="text" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Telephone <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="tel" id="id_phonenumber_in" name="phonenumber_in" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">E-mail <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="email" required="required" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Address <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="address_1" required="required" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">&nbsp;
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="address_2"  class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">&nbsp;
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="address_3" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Post Code/Zip Code<span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="address_4" required="required" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Country<span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_country" name="country" required="required" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Description<span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                <textarea id="message" required="required" class="form-control" name="profile_text" data-parsley-trigger="keyup" data-parsley-minlength="20" data-parsley-maxlength="10000" data-parsley-minlength-message="Profile must be least a 20 characters long..." data-parsley-validation-threshold="1"  onkeyup="textAreaAdjust(this)" style="overflow:hidden">
                  </textarea>
                </div>
              </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Website
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="website" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Facebook
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="facebook" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Twitter
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="twitter" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Instagram
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="id_hull_colour" name="instagram" class="form-control col-md-7 col-xs-12" >
                  </div>
                </div>
                
               
                
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    <button type="submit" class="btn btn-danger btn-round" id="submit_button" >Create Sponsor</button>
                  </div>
                </div>
              </form>
            </div>
            
        </div>
      </div>
    </div>   
  </div>
  

</div>

<script>



</script>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- Chart.js -->
  <script src="/static/vendors/Chart.js/dist/Chart.min.js"></script>
  <!-- gauge.js -->
  <script src="/static/vendors/gauge.js/dist/gauge.min.js"></script>
  <!-- Skycons -->
  <script src="/static/vendors/skycons/skycons.js"></script>
  <!-- Flot -->
  <script src="/static/vendors/Flot/jquery.flot.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.pie.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.time.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.stack.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.resize.js"></script>
  <!-- Flot plugins -->
  <script src="/static/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
  <script src="/static/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
  <script src="/static/vendors/flot.curvedlines/curvedLines.js"></script>
  <!-- DateJS -->
  <script src="/static/vendors/DateJS/build/date.js"></script>
  <!-- JQVMap -->
  <script src="/static/vendors/jqvmap/dist/jquery.vmap.js"></script>
  <script src="/static/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
  <script src="/static/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
  <!-- Data Tables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
  <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
  <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
  <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>
  <!-- File Upload -->
  <script src="/static/vendors/jquery-file-upload/js/vendor/jquery.ui.widget.js"></script>
  <script src="/static/vendors/jquery-file-upload/js/jquery.iframe-transport.js"></script>
  <script src="/static/vendors/jquery-file-upload/js/jquery.fileupload.js"></script>
  <script src="/static/vendors/intl-tel-input/build/js/intlTelInput.js"></script>
  <script>

  function init_countries() {

    var countries = { {% for country in countries %}{{ country.code }} : "{{country.name }} [{{ country.code }}]", {% endfor %}};

    var countriesArray = $.map(countries, function(value, key) {
        return {
            value: value,
            data: key
        };
    });

    // initialize autocomplete with custom appendTo
    $('#id_country').autocomplete({
        lookup: countriesArray
    })

  };

  function textAreaAdjust(o) {
  o.style.height = "1px";
  o.style.height = (25+o.scrollHeight)+"px";
};

    $(document).ready(function() {
  init_countries();

    $('#btn_id').click(function(event){
      $('#id_license').click();
    });

  $('#id_license').on('change', function(event){
      $('#btn_id').html('<i class="fa fa-check"></i> File Uploaded');
      $('#btn_id').removeClass('btn-danger');
      $('#btn_id').addClass('btn-success');
  })

});
  </script>

  <script>
    var input = document.querySelector("#id_phonenumber_in");

    window.intlTelInput(input, {
       allowDropdown: true,
      // autoHideDialCode: false,
      // autoPlaceholder: "off",
      // dropdownContainer: document.body,
      // excludeCountries: ["us"],
      // formatOnDisplay: false,
      hiddenInput: "phonenumber",
      initialCountry: "gb",
      // localizedCountries: { 'de': 'Deutschland' },
      // nationalMode: false,
      // onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
      // placeholderNumberType: "MOBILE",
      preferredCountries: ['gb', 'hk'],
      // separateDialCode: true,
      utilsScript: "/static/vendors/intl-tel-input/build/js/utils.js",
    }){% if racer.telephone_number %}.setNumber("{{ racer.telephone_number }}"){% endif %};
    

  </script>


{% endblock javascripts %}