boats/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from . import views
app_name = 'boats'
urlpatterns = [
	url(r'^boat/(?P<boat_id>[0-9]+)/$', views.view_boat, name='view_boat'),
	url(r'^engine/(?P<engine_id>[0-9]+)/$', views.view_engine, name='view_engine'),
	url(r'^uploadboatimage/(?P<boat_id>[0-9]+)/$', views.upload_boat_image, name='upload_boat_image'),
	url(r'^updateboat/(?P<boat_id>[0-9]+)/$', views.update_boat, name='update_boat'),
	url(r'^updateengine/(?P<engine_id>[0-9]+)/$', views.update_engine, name='update_engine'),
	url(r'^engineservice/(?P<engine_id>[0-9]+)/$', views.add_service, name='update_service'),
	url(r'^deleteboatimage/(?P<image_id>[0-9]+)/$', views.delete_boat_image, name='delete_boat_image'),
	url(r'^addboat/$', views.add_boat, name='add_boat'),
	url(r'^addengine/$', views.add_engine, name='add_engine'),
	url(r'^createboat/$', views.create_boat, name='create_boat'),
	url(r'^createengine/$', views.create_engine, name='create_engine'),
	url(r'^engines/$', views.index_engines, name='engines_index'),
    url('', views.index, name='index'),
]

powerboatsapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^login/$', auth_views.login, {'template_name': 'login.html'},name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^internal/boats/', include('boats.urls')),
    url(r'^internal/members/', include('racers.urls')),
    url(r'^internal/sponsors/', include('sponsors.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

racers/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

from . import views
app_name = 'racers'
urlpatterns = [
	url(r'^racer/(?P<racer_id>[0-9]+)/$', views.user_profile, name='view_user'),
	url(r'^uploadracerimage/(?P<person_id>[0-9]+)/$', views.upload_profile_image, name='upload_profile_image'),
	url(r'^updateprofile/(?P<racer_id>[0-9]+)/$', views.profile_update, name='profile_update'),
	url(r'^addvictory/(?P<racer_id>[0-9]+)/$', views.add_victory, name='add_victory'),
	url(r'^profiletext/(?P<racer_id>[0-9]+)/$', views.profile_text, name='profile_text'),
	url(r'^addlicense/(?P<racer_id>[0-9]+)/$', views.add_license, name='add_license'),
	url(r'^addidentity/(?P<racer_id>[0-9]+)/$', views.add_identity, name='add_identity'),
	url(r'^deleteprofileimage/(?P<image_id>[0-9]+)/$', views.delete_profile_image, name='delete_profile_image'),
    url('', views.index, name='index'),
]

racers/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from datetime import datetime
from dateutil.relativedelta import relativedelta
# Create your models here.

#
# Racing Licenses
# 

class RacingLicenseTypes(models.Model):
	name = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name 

class RacingLicenseScans(models.Model):
	file = models.FileField(upload_to='licenses')
	expires = models.DateField()
	uploaded_date = models.DateTimeField(auto_now_add=True)
	license_type = models.ForeignKey(RacingLicenseTypes, null=True)

	def expiry_dt(self):
		exp_dt = datetime.strptime((self.expires).strftime('%Y-%m-%d'), '%Y-%m-%d').strftime('%Y-%m-%dT%H:%M:%S.%f')
		exp_dt = datetime.strptime(exp_dt, '%Y-%m-%dT%H:%M:%S.%f')
		return exp_dt
#
# Identity Documents
#

class IdentityTypes(models.Model):
	name = models.CharField(max_length=250)

	def __unicode__(self):
		return self.name 

class IdentityScans(models.Model):
	file = models.FileField(upload_to='identity')
	expires = models.DateField()
	uploaded_date = models.DateTimeField(auto_now_add=True)
	identity_type = models.ForeignKey(IdentityTypes)

	def expiry_dt(self):
		exp_dt = datetime.strptime((self.expires).strftime('%Y-%m-%d'), '%Y-%m-%d').strftime('%Y-%m-%dT%H:%M:%S.%f')
		exp_dt = datetime.strptime(exp_dt, '%Y-%m-%dT%H:%M:%S.%f')
		return exp_dt

#
# Driver Profile Images
#

class DriverProfile(models.Model):
	file = models.FileField(upload_to='profile')
	uploaded_date = models.DateTimeField(auto_now_add=True)
	profile_image = models.BooleanField(default=False)

class CareerVictory(models.Model):
	name = models.CharField(max_length=250)
	location = CountryField(null=True)
	team = models.CharField(max_length=250, null=True)
	year = models.CharField(max_length=250)
	position = models.CharField(max_length=2)

#
# Drivers Main Model
#

class Members(models.Model):
	username = models.ForeignKey(User, null=True)
	country = CountryField()
	license_types = models.ManyToManyField(RacingLicenseTypes)
	licenses = models.ManyToManyField(RacingLicenseScans)
	identity = models.ManyToManyField(IdentityScans)
	facebook_handle = models.CharField(max_length=250, null=True, blank=True)
	twitter_handle = models.CharField(max_length=250, null=True, blank=True)
	insta_handle = models.CharField(max_length=250, null=True, blank=True)
	personal_site = models.CharField(max_length=250, null=True, blank=True)
	profile_images = models.ManyToManyField(DriverProfile)
	profile_text = models.TextField(null=True, blank=True)
	email_address = models.EmailField(max_length=254)
	telephone_number = PhoneNumberField(null=True)
	address_line_1 = models.CharField(max_length=250)
	address_line_2 = models.CharField(max_length=250, null=True, blank=True)
	address_line_3 = models.CharField(max_length=250, null=True, blank=True)
	address_line_4 = models.CharField(max_length=250, null=True, blank=True)
	address_country = CountryField(null=True)
	years_experience = models.IntegerField(null=True)
	career_victories = models.ManyToManyField(CareerVictory)
	registered_date = models.DateTimeField(auto_now_add=True)
	terms_conditions = models.BooleanField(default=False)
	terms_conditions_date = models.DateTimeField(auto_now_add=True)
	racer = models.BooleanField(default=False)
	sponsor = models.BooleanField(default=False)
	date_of_birth = models.DateField(null=True)
	supplier = models.BooleanField(default=False)
	email_address = models.CharField(max_length=250, null=True)
	active = models.BooleanField(default=False)

	def profile_image(self):
		profile = self.profile_images.filter(profile_image=True)[0]
		return profile.file

	def get_current_age(self):
		age = relativedelta(datetime.now().date(), self.date_of_birth).years
		return age

racers/forms.py
from django import forms
from .models import *

class PersonForm(forms.Form):
	phonenumber = forms.CharField(required=False)
	dob = forms.CharField(required=False)
	nationality = forms.CharField(required=False)
	address_1 = forms.CharField(required=False)
	address_2 = forms.CharField(required=False)
	address_3 = forms.CharField(required=False)
	address_4 = forms.CharField(required=False)
	home_country = forms.CharField(required=False)
	personal = forms.CharField(required=False)
	facebook = forms.CharField(required=False)
	twitter = forms.CharField(required=False)
	instagram = forms.CharField(required=False)

class EventForm(forms.Form):
	event = forms.CharField(required=False)
	event_location = forms.CharField(required=False)
	team = forms.CharField(required=False)
	year = forms.CharField(required=False)
	position = forms.CharField(required=False)

class ProfileForm(forms.Form):
	profile_text = forms.CharField(widget=forms.Textarea)

class LicenseForm(forms.Form):
	license = forms.FileField(widget=forms.ClearableFileInput())
	expiry_date = forms.CharField(required=False)
	licensetype = forms.CharField(required=False)

class IdentityForm(forms.Form):
	identity = forms.FileField(widget=forms.ClearableFileInput())
	expiry_date = forms.CharField(required=False)
	identitytype = forms.CharField(required=False)

racers/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views import View
from datetime import datetime
from django.urls import reverse
from django_countries.fields import Country, countries

from .models import *
from .forms import *
from boats.forms import PhotoForm
# Create your views here.

def check_user(request, id):
	member = Members.objects.get(id=id)
	if request.user.id == member.username.id:
		return True
	elif user.is_staff == True:
		return True
	else:
		return False

@login_required(login_url='/login/')
def index(request):
	racers = Members.objects.filter(racer=True)
	context = {
    	'racers' : racers,
	}
	template = loader.get_template('racers/index.html')
	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def user_profile(request, racer_id):
	cu = check_user(request, racer_id)

	racer = Members.objects.get(id=racer_id)
	victories = racer.career_victories.all().order_by("-year")
	licenses = RacingLicenseTypes.objects.all()
	identities = IdentityTypes.objects.all()
	racer_licenses = racer.licenses.all().order_by("-expires")
	racer_identities = racer.identity.all().order_by("-expires")
	context = {
    	'racer' : racer,
    	'countries' : countries,
    	'victories' : victories,
    	'licenses' : licenses,
    	'racer_licenses' : racer_licenses,
    	'identities' : identities,
    	'racer_identities' : racer_identities,
	}

	if cu == False:
		template = loader.get_template('racers/profile_santized.html')
	else:
		template = loader.get_template('racers/profile.html')

	return HttpResponse(template.render(context, request))

@login_required(login_url='/login/')
def add_license(request, racer_id):
	cu = check_user(request, racer_id)
	if cu == False:
		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

	racer = Members.objects.get(id=racer_id)

	if request.method == "POST":
		form = LicenseForm(request.POST,request.FILES)
		scan = request.FILES.get('license')
		if form.is_valid():
			r_l = RacingLicenseScans(file=scan)
			r_l.expires = datetime.strptime(form.cleaned_data['expiry_date'], "%d/%m/%Y")
			lic_type = RacingLicenseTypes.objects.get(id=form.cleaned_data['licensetype'].split("[")[1].split("]")[0])
			r_l.license_type = lic_type
			r_l.save()
			racer.licenses.add(r_l)
			racer.save()
	
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def add_identity(request, racer_id):
	cu = check_user(request, racer_id)
	if cu == False:
		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

	racer = Members.objects.get(id=racer_id)

	if request.method == "POST":
		form = IdentityForm(request.POST,request.FILES)
		scan = request.FILES.get('identity')
		print(form.errors)
		if form.is_valid():
			r_l = IdentityScans(file=scan)
			r_l.expires = datetime.strptime(form.cleaned_data['expiry_date'], "%d/%m/%Y")
			lic_type = IdentityTypes.objects.get(id=form.cleaned_data['identitytype'].split("[")[1].split("]")[0])
			r_l.identity_type = lic_type
			r_l.save()
			racer.identity.add(r_l)
			racer.save()
	
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def add_victory(request, racer_id):
	cu = check_user(request, racer_id)
	if cu == False:
		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

	racer = Members.objects.get(id=racer_id)
	if request.method == "POST":
		form = EventForm(request.POST)
		if form.is_valid():
			victory = CareerVictory(name=form.cleaned_data['event'])
			victory.location = form.cleaned_data['event_location'].split("[")[1].split("]")[0]
			victory.team = form.cleaned_data['team']
			victory.year = form.cleaned_data['year']
			victory.position = form.cleaned_data['position']
			victory.save()
			racer.career_victories.add(victory)
			racer.save()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required(login_url='/login/')
def profile_text(request, racer_id):
	cu = check_user(request, racer_id)
	if cu == False:
		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

	racer = Members.objects.get(id=racer_id)
	if request.method == "POST":
		form = ProfileForm(request.POST)
		if form.is_valid():
			racer.profile_text = form.cleaned_data['profile_text']
			racer.save()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))		

@login_required(login_url='/login/')
def profile_update(request, racer_id):
	cu = check_user(request, racer_id)
	if cu == False:
		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

	racer = Members.objects.get(id=racer_id)
	if request.method == "POST":
		form = PersonForm(request.POST)
		print(form.errors)
		if form.is_valid():
			phonenumber = form.cleaned_data['phonenumber']
			dob = form.cleaned_data['dob']
			nationality = form.cleaned_data['nationality']
			address_1 = form.cleaned_data['address_1']
			address_2 = form.cleaned_data['address_2']
			address_3 = form.cleaned_data['address_3']
			address_4 = form.cleaned_data['address_4']
			home_country = form.cleaned_data['home_country']
			personal = form.cleaned_data['personal']
			twitter  = form.cleaned_data['twitter']
			instagram  = form.cleaned_data['instagram']
			facebook  = form.cleaned_data['facebook']

			racer.date_of_birth = datetime.strptime(dob, '%d/%m/%Y')
			racer.telephone_number = phonenumber
			racer.address_line_1 = address_1
			racer.address_line_2 = address_2
			racer.address_line_3 = address_3
			racer.address_line_4 = address_4
			racer.address_country = home_country.split("[")[1].split("]")[0]
			racer.country = nationality.split("[")[1].split("]")[0]
			racer.facebook_handle = facebook
			racer.insta_handle = instagram
			racer.twitter_handle = twitter
			racer.personal_site = personal
			racer.save()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def upload_profile_image(request, person_id):
	cu = check_user(request, racer_id)
	if cu == False:
		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

	person = Members.objects.get(id=person_id)
	if request.method == "POST":
		form = PhotoForm(request.POST, request.FILES)
		files = request.FILES.getlist('boat_image')
		if form.is_valid():
			for f in files:
				boat_image = DriverProfile(file=f)
				boat_image.save()
				person.profile_images.add(boat_image)
				person.save()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

@login_required(login_url='/login/')
def delete_profile_image(request, image_id):
	cu = check_user(request, racer_id)
	if cu == False:
		return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
	person_image = DriverProfile.objects.get(id=image_id).delete()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

racers/templates/racers/index.html
{% extends "base_site.html" %}

{% block title %} Boats Administration {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="page-title">
        <div class="title_left">
          <h3>APA Racers</h3>
        </div>

      </div>
    
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel tile">
          <div class="x_title">
            <h2>All Registered Competitors</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
             <p class="text-muted font-13 m-b-30">
                All boats are displayed in the table below, the search function is dynamic. Click on the boat regisration to modify the boat.
              </p>
              <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Nationality</th>
                    <th>Home Country</th>
                    <th>E-mail</th>
                    <th>Telephone</th>
                  </tr>
                </thead>


                <tbody>
                  {% for racer in racers %}
                  <tr>
                    <td align="center"><a href="{% url 'racers:view_user' racer.id %}">{{ racer.username.first_name }} {{ racer.username.last_name }}</a></td>
                    <td align="center"><i class="flag1x {{ racer.country.flag_css }}"></i>&nbsp;{{ racer.country.name }}</td>
                    <td align="center"><i class="flag1x {{ racer.address_country.flag_css }}"></i>&nbsp;{{ racer.address_country.name }}</td>
                    <td align="center"><a href="mailto:{{ racer.username.username }}?APA Contact">{{ racer.username.username }}</a></td>
                    <td align="center"><a href="tel:{{ racer.telephone_number }}t">{{ racer.telephone_number }}</a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
          </div>
        </div> 
      </div>
    </div>
    <div class="page-title">
        <div class="title_left">
          <h4>Profile View</h4>
        </div>
    </div>
    {% for racer in racers %}
    <div class="row">
      <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="x_panel tile">
          <div class="x_title">
            <h2><i class="flag1x {{ racer.country.flag_css }}"></i>&nbsp;{{ racer.username.first_name }} {{ racer.username.last_name }}</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="thumbnail">
              <div class="image view view-first">
                <img style="width: 100%; display: block;" src="{{ racer.profile_image.url }}" alt="image" />    
              </div>
            </div>
            <table class="countries_list">
              <tbody>
                <tr>
                  <td>Name</td>
                  <td class="fs15 fw700 text-right">{{ racer.username.first_name }} {{ racer.username.last_name }}</td>
                </tr>
                <tr>
                  <td>Nationality</td>
                  <td class="fs15 fw700 text-right"><i class="flag1x {{ racer.country.flag_css }}"></i> {{ racer.country.name }}</td>
                </tr>
                <tr>
                  <td>Home Country</td>
                  <td class="fs15 fw700 text-right"><i class="flag1x {{ racer.address_country.flag_css }}"></i> {{ racer.address_country.name }}</td>
                </tr>
                <tr>
                  <td>DoB (Age)</td>
                  <td class="fs15 fw700 text-right">{{ racer.date_of_birth|date:'d/m/Y' }} ({{racer.get_current_age}})</a></td>
                </tr>
                <tr>
                  <td>Telephone</td>
                  <td class="fs15 fw700 text-right"><a href="tel:{{ racer.telephone_number }}t">{{ racer.telephone_number }}</a></td>
                </tr>
                <tr>
                  <td>E-mail</td>
                  <td class="fs15 fw700 text-right"><a href="mailto:{{ racer.username.username }}?APA Contact">{{ racer.username.username }}</a></td>
                </tr>
              </tbody>
            </table>
            <p align="center"><a href="{% url 'racers:view_user' racer.id %}" class="btn btn-round btn-danger">View Profile</a></p>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
      
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- Chart.js -->
  <script src="/static/vendors/Chart.js/dist/Chart.min.js"></script>
  <!-- gauge.js -->
  <script src="/static/vendors/gauge.js/dist/gauge.min.js"></script>
  <!-- Skycons -->
  <script src="/static/vendors/skycons/skycons.js"></script>
  <!-- Flot -->
  <script src="/static/vendors/Flot/jquery.flot.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.pie.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.time.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.stack.js"></script>
  <script src="/static/vendors/Flot/jquery.flot.resize.js"></script>
  <!-- Flot plugins -->
  <script src="/static/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
  <script src="/static/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
  <script src="/static/vendors/flot.curvedlines/curvedLines.js"></script>
  <!-- DateJS -->
  <script src="/static/vendors/DateJS/build/date.js"></script>
  <!-- JQVMap -->
  <script src="/static/vendors/jqvmap/dist/jquery.vmap.js"></script>
  <script src="/static/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
  <script src="/static/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
  <!-- Data Tables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
  <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
  <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
  <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>
{% endblock javascripts %}